### ISSUE TITLE
Trouble with exitKiosk with a Cordova/Ionic app

### ISSUE THREAD

**Issue by IronWill79** [honza889/cordova-plugin-kiosk#10]
Hi,

I am a relatively newbie to Cordova development and am making a kiosk-style app. I have added your plugin and added the code in your demo, but I cannot get it to exit to application. I have tried using inline script with the onclick event as in your demo code (with the inline-unsafe exception) and also as an ng-click with the AngularJS controller executing the Javascript call to KioskPlugin, but nothing seems to work. The other function isInKiosk also doesn't work. It appears to be possibly not accessing the plugin, but I could imagine it could be a conflict with Ionic/AngularJS although not sure how.

Can you give me any assistance in this? Thanks in anticipation of your reply and wonderful work on the plugin. Even though I can't get the functions to work, the rest of the functionality seems to be intact, locking the device down nicely.

Regards, Neil

**Comment by thaarok** [comment]
The AngularJS and Ionic cannot be a problem - I have used it with them.
To debug cordova application (and to obtain error message) you can use following tutorial:
http://geeklearning.io/apache-cordova-and-remote-debugging-on-android/

**Comment by IronWill79** [comment]
Thanks a lot for that. I thought I had an issue with my code. I will continue my debugging on the webview end with the link you sent. You are a lifesaver!
