### ISSUE TITLE
Enable or Disable Kioskmode at Appstart (flagdepending)

### ISSUE THREAD

**Issue by Giusti** [honza889/cordova-plugin-kiosk#11]
Hey honza,

Thank you very much for the plugin, I was wondering if it is possible to make the Kiosk mode settings depending, so that when the App starts a Flag decides if the kiosk mode is enabled or disabled. A szenario  would be that the Admin can toggle Kiosk mode in the App settings which will be saved in the local Storage so when it is disabled the next time the App starts it wont be in kiosk mode anymore?

I dont have much java knowledge, but I think If I add a function to the kiosk.js and add an action to the java execute function this could work ?

Regards
Christopher

**Comment by thaarok** [comment]
The Kiosk mode is turned on by setting the application as launcher. Admin have to set launcher in phone settings, the application cannot change this. Application can only detect if it is in kiosk mode and allow to escape it.

**Comment by Giusti** [comment]
Ah okay thank you
