### ISSUE TITLE
Back button goes to recent screens

### ISSUE THREAD

**Issue by madlandproject** [honza889/cordova-plugin-kiosk#12]
Using an emulator, and on a Samsung Galaxy View with Android v5.1 it is possible to leave the app using the back button (the recent screens button is locked as intended). I have very little experience with Cordova and Android in general so I'm not sure what other information I can supply to help. I know it's possible, having seen this in SecureLock, but haven't figured out how to get it working with Cordova.

**Comment by thaarok** [comment]
The back button is not captured by this plugin to allow application to handle it - use cordova events to capture it:
https://cordova.apache.org/docs/en/4.0.0/cordova/events/events.backbutton.html
