### ISSUE TITLE
Can't exit permanently

### ISSUE THREAD

**Issue by yskristiawan** [honza889/cordova-plugin-kiosk#13]
Hi.

First: thanks for building the plugin, it is very useful.

I am compiling the demo (unchanged) using Phonegap Build. I add `<plugin name="cordova-plugin-kiosk" spec="https://github.com/honza889/cordova-plugin-kiosk.git" source="git" />` in the config.xml.

Everything is working well, except the KioskPlugin.exitKiosk() part. It show the "Select destination.." popup, when I tap another launcher, it switch to that launcher, BUT when I tap the android home button, it show the kiosk plugin demo again instead of the launcher that I just select.

Is there any solution for this?

Thanks a lot for your help. I really appreciate it...

![launcher](https://cloud.githubusercontent.com/assets/23466874/20347362/4c58dcb6-ac33-11e6-87bb-c95053335137.jpeg)

**Comment by thaarok** [comment]
Sorry, it would require to change the launcher from app and it is impossible to do from non-system app.
(and system app would not be possible to install to non-rooted device + it would be much more complicated to install)

**Comment by yskristiawan** [comment]
OK. Thanks a lot!
