### ISSUE TITLE
Touch doesn't work under StatusBar-Area  

### ISSUE THREAD

**Issue by basecode** [honza889/cordova-plugin-kiosk#14]
I have a simple fullscreen app where 100% of the area is touchable/clickable. As soon as I turn on kiosk mode the area under the (hidden) StatusBar is not touchable anymore.

I haven't tried to follow the steps described [here](https://developer.android.com/training/system-ui/status.html#40) yet in order to isolate the issue without the kiosk plugin.

My general question would be:
- Is this a known issue or maybe related to a specific Android version? I'm using Android – 5.0 Lollipop
- Could it be that your code is optimised for 4.0 or older? The docs mentioning for 4.1 and higher it is recommended to use:
```java
View decorView = getWindow().getDecorView();
// Hide the status bar.
int uiOptions = View.SYSTEM_UI_FLAG_FULLSCREEN;
decorView.setSystemUiVisibility(uiOptions);
// Remember that you should never show the action bar if the
// status bar is hidden, so hide that too if necessary.
ActionBar actionBar = getActionBar();
actionBar.hide();
```

Thank you for taking the time to look into my issue :)

**Comment by thaarok** [comment]
Yes, I was keeping support for Android 4.0. But maybe it is useless already...

You can try to add the code above into `cordova-plugin-kiosk/android/KioskActivity.java`:
https://github.com/honza889/cordova-plugin-kiosk/blob/master/android/KioskActivity.java#L40
And re-add platform to re-generate java files:
`cordova platform rm android` + `cordova platform add android`

If it will work better, feel free to send pull request.

**Comment by pcoenen** [comment]
I'm strugling with the same problem, so I was wondering  where did you added this code and did it work?

**Comment by thaarok** [comment]
@pcoenen It should be added to the end of onCreate() method - see link above. (But have no idea if it work, have no chance to test it yet... that is why it is not in upstream)

**Comment by basecode** [comment]
@pcoenen I was mostly concerned about Android 4.4 upwards + immersive fullscreen-mode. A possible solution can be found here (code is still under testing). https://github.com/adobe-rnd/cordova-plugin-kiosk/commit/628a0b7accb9ae9d90e011c6131b0898ff1567b3.
Unfortunately the code can't easily merged back.

**Comment by rabbishuki** [comment]
@basecode finished testing? can we use it?

**Comment by thaarok** [comment]
Merged in master now.

**Comment by rabbishuki** [comment]
does this mean that issue #15 is also solved?
