### ISSUE TITLE
I am able to open the notification panel

### ISSUE THREAD

**Issue by fedme** [honza889/cordova-plugin-kiosk#15]
I am able to swipe down from the top of the screen and than swipe down again when the status bar appears. This way I can successfully open the notification panel and change the quick settings (i.e. turn on/off wifi). Tested on Android 7.1.1.

![photo5900268845833234511](https://cloud.githubusercontent.com/assets/3295133/23589515/e45e12b0-01ce-11e7-9776-c9bd22e11fcf.jpg)

Any idea how to solve this?

**Comment by thaarok** [comment]
This should be solved using ACTION_CLOSE_SYSTEM_DIALOGS intent, which is sent on window focus change:
https://github.com/honza889/cordova-plugin-kiosk/blob/master/android/KioskActivity.java#L49
You can try to modify/add more Timers (like on line 59-65), which send this request to close system dialogs also after short delay, as immediate request is ignored by notification area sometime.

If you use Android 4.1+, you can try to use way of blocking suggested in https://github.com/honza889/cordova-plugin-kiosk/issues/14 - feel free to sent pull request if it will be working.

**Comment by fedme** [comment]
Thanks for the fast reply,
I'm not interested in 4.1- so I'm gonna try #14  and report the results

**Comment by rabbishuki** [comment]
@raimaj @honza889 
Found a good enough solution if you are running android 6+.

Apparently you can hide all the option in the  the quick settings.

Steps to Remove Status Bar Icons:
===

- **Step 1:** First of all you have to enable System UI Tuner. For that, expand the **Quick Settings panel** by swiping down from top of the screen twice.
- **Step 2:** At the top right side of Quick Settings panel, you’ll see a **gear icon**. It is similar to that of Google Android settings application. Tap and hold the gear icon.
- **Step 3:** The gear icon will start to spin. Hold it for a few seconds and the release it.
- **Step 4:** After you let go the gear icon, you will see the toast message at the bottom of the screen.
- **Step 5:** In **Settings**, you will need to scroll down the page to find the **SystemUI Tuner**’s option. Tap it.
- **Step 6:** Here, you’ll see an option of the Status Bar. Tap on it to see the list of all the toggles.
remove Status Bar icons
- **Step 7:** Toggle all the icons off, one at a time. These icons will no more be visible next time when they are in use/active.

![itechify-statusbar-169x300 1](https://user-images.githubusercontent.com/24904197/32369875-b2985ffe-c093-11e7-82c3-35be03354abe.jpg)

These simple steps will help you to remove Status Bar icons

**Comment by thaarok** [comment]
Please retest with latest version - should be fixed by https://github.com/hkalina/cordova-plugin-kiosk/pull/47
Reopen this issue if not resolved.
