### ISSUE TITLE
Exit from kiosk mode in app

### ISSUE THREAD

**Issue by hrupin** [honza889/cordova-plugin-kiosk#16]
Hello. 

Thanks for a wonderful app. But I can't get out of kiosk mode of the application. Use command KioskPlugin.exitKiosk(); onclick button. But I'm still in kiosk mode

**Comment by thaarok** [comment]
Hi, **KioskPlugin.exitKiosk()** call should show launcher selection box - you need to select your usual launcher after. (Like this one: https://cloud.githubusercontent.com/assets/23466874/20347362/4c58dcb6-ac33-11e6-87bb-c95053335137.jpeg ) Was this dialog shown, or it just didnt show anything?

Please try to use Chrome remote debug to obtain more info (error message) if this is not your problem:
http://ourcodeworld.com/articles/read/48/how-to-debug-a-cordova-app-on-your-device-with-google-chrome
Thanks

**Comment by hrupin** [comment]
Initially, using js trigger method KioskPlugin.exitKiosk()

I made two buttons in the file HomeActivity.java. One start, the second exit. And hung on click method 

private void exitFromApp() {
System.exit(0);
}

The app closes and opens again  Kiosk Mode

Errors in console no. This way I catch errors. But it is clean.

**Comment by thaarok** [comment]
The Kiosk app is set as launcher - you cannot close it using System.exit() - you need to start regular launcher using intent. That is what KioskPlugin.exitKiosk() do. Behavior you describe is intended.

**Comment by hrupin** [comment]
When I call KioskPlugin.exitKiosk() appears in the app selection and trebushet when you choose app then again run kiosk mode when you choose the second item (trebushet) that seems closed, but after a second kiosk mode starts again.

**Comment by hrupin** [comment]
Thanks for the replies. 
When you choose your application window appears 'Click or press any key to begin...' with any pressing goes into the kiosk.

**Comment by hrupin** [comment]
I made a video where I attempt to exit kiosk mode in the demo application https://github.com/honza889/cordova-kiosk-demo

https://youtu.be/BVIrKmxMgPc

**Comment by thaarok** [comment]
Yes, behavior you demonstrate is intended. It is the only way how can kiosk mode using custom launcher work - you need to use exitKiosk to escape from app, go to the settings and change launcher for permament kiosk escape.
