### ISSUE TITLE
Disable auto kiosk mode

### ISSUE THREAD

**Issue by ramezrafla** [honza889/cordova-plugin-kiosk#19]
@honza889 
Thanks again for a great app!

We want to include your plugin in a production app but want to enable kiosk mode manually (so admins enter password) rather than at startup for some devices.

If you can guide me, we can work on it and maybe do a PR. It would be very appreciated as it is very technical and requires experience in the different intents.

Thanks!

**Comment by thaarok** [comment]
Sorry, but kiosk mode require the app is set as launcher - setting of launcher can be changed only manually by user or with system app permissions (which you can obtain only on rooted devices).

**Comment by ramezrafla** [comment]
Excellent! So that means as long as we password protect the change of launcher app with a password we can safely publish the app in google play, right?

**Comment by thaarok** [comment]
Yes. It should not be problem.
