### ISSUE TITLE
Prompt to click to begin

### ISSUE THREAD

**Issue by remi-grumeau** [honza889/cordova-plugin-kiosk#2]
Hi,

Android boots up on this kiosk app which is wonderful.

Only issue is it prompts me to tap before it loads on startup.
Since a kiosk should boot up by its own every morning, that's kind of a problem.

Here is a video showing the problem https://www.youtube.com/watch?v=RocIgTV_ttw

App is the demo one, with zero modifications. Build done on OS X 10.11.4 with cordova 6.0.0
Tablet is from a chinese vendor, running a stock Android 4.2.2 (kernel 3.0.50).

Remi

**Comment by yoldar** [comment]
Thank you Remi for testing this plugin on android! I have a task to test it and you saved my time :) BTW on the video I couldn't find where prompt occurred.

**Comment by remi-grumeau** [comment]
Prompt is not as a promptWindow, but as a text on startup.

You can see in the video that i have to tap on the screen in order to start the app. Otherwise it just stays on a grey screen with a text in black "click to begin..."

Remi

**Comment by remi-grumeau** [comment]
This is the screen i'm talking about

Remi

**Comment by remi-grumeau** [comment]
Ok my bad, it shows a few seconds but then the app loads. 

Would be nice to replace this by a black screen btw :)

Remi

**Comment by thaarok** [comment]
Hi @remi-grumeau, the reason for this startup screen is , that if it starts directly into CordovaActivity, the resources are not available yet, so application fail to start with message:

> Application Error - The connection to the server was unsuccessful. (file:///android_asset/www/index.html)

Replacement by blank screen sounds good. I will add it.

**Comment by arch1v1st** [comment]
+1 - Also wish this would just display a black screen!

**Comment by thaarok** [comment]
Looks like @babbelLab has already resolved this samehow:
https://github.com/babbelLab/cordova-plugin-kiosk

**Comment by arch1v1st** [comment]
Thanks for that, Honza (AND @babbelLab)!  This indeed solves my issues.  Consider this issue closed.

**Comment by arch1v1st** [comment]
@babbelLab - there is an issue with startup - if the app starts before boot has completed then connectivity may be an problem.  We are adapting our app to handle that and retry, but for others I would suggest blocking until a BOOT_COMPLETED has been triggered.

Your contributions are much appreciated :)

**Comment by lavindika** [comment]
Honza (AND @babbelLab) I have an issue with startup.App lock works fine after i put the app launcher always.then i unlock and restart the device.My application start and stop at my splash screen.at lest not working function .document.addEventListener('deviceready', function () {} also.please help me.

**Comment by thaarok** [comment]
@lavindika You can try obtain more information using Google Chrome on PC connected to device - see
https://gonzalo123.com/2014/08/04/debugging-android-cordovaphonegap-apps-with-chrome/
If not directly related to this thread, consider create standalone issue and specify version (commit hash).

**Comment by lavindika** [comment]
Your solution save my day.This is very good approach of kisok mode application.My application works fine in a different device LG tablet.Problem i found android 5.1 sony experia Z when the device reboot.**I have another question?**I there a availability of handling a chooser without giving user to chose which application by checking is 
if(isInKiosk){
      //select home as default application
}
else{
    //select my application as default application
}.
for eg:lets say i have a button call lock.when the user press lock button.then check isInKiosk or no.if is it in kisok auto select home as default.if not select my select myapplauncher.I think  @honza889 and @babbelLab will help me.Thank you.

**Comment by thaarok** [comment]
If I understand your question correctly, you want to change launcher app from your app to start/stop kiosk mode. I don't think it is possible (at least without root). (At least I was unable to do it when I was trying to do the same.)

**Comment by lavindika** [comment]
Thanks Boss your reply.yes i tired.But i found some things we can reset the launcher and call new intent without create chooser then comes all permissions with default and always.Then i found isInKiosk some issues in android.brother Im not a android developer please help me.

(1) this one for clear the launcher 

```
 **else if (EXIT_KIOSK.equals(action)) {
              PackageManager packageManager = this.cordova.getActivity().getPackageManager();
              packageManager.clearPackagePreferredActivities(this.cordova.getActivity().getPackageName());
              Intent intent = new Intent(Intent.ACTION_MAIN);
              intent.addCategory(Intent.CATEGORY_HOME);
              SharedPreferences sp = PreferenceManager.getDefaultSharedPreferences(this.cordova.getActivity().getApplicationContext());
              sp.edit().putBoolean(PREF_KIOSK_MODE, false).commit();
             if (intent.resolveActivity(cordova.getActivity().getPackageManager()) != null) {
                cordova.getActivity().startActivity(intent);
             }
            return true;
        }**
```

(2) This one for check is my launcher isset 
  **public boolean isMyLauncherDefault() {
    final IntentFilter filter = new IntentFilter(Intent.ACTION_MAIN);
    filter.addCategory(Intent.CATEGORY_HOME);
    List<IntentFilter> filters = new ArrayList<IntentFilter>();
    filters.add(filter);
    final String myPackageName = this.cordova.getActivity().getPackageName();
    List<ComponentName> activities = new ArrayList<ComponentName>();
    final PackageManager packageManager = (PackageManager) this.cordova.getActivity().getPackageManager();
    // You can use name of your package here as third argument
    packageManager.getPreferredActivities(filters, activities, null);
    for (ComponentName activity : activities) {
        if (myPackageName.equals(this.cordova.getActivity().getPackageName())) {
            return true;
        }
    }
    return false;
}**

please tell me am i correct or no.Your are genius to to help me :+1:

**Comment by thaarok** [comment]
1) The first solution suppose your app is the only kiosk application. If you will test/use more similar apps on one device, your EXIT_KIOSK can start any other launcher.

2) If you know target device, you can start usual launcher using custom intent.

If you dont know what is usual launcher of the target device, I would prefer to keep chooser here.

The second one looks like it could work, but I now have no space to test it. If it works for you, pull request is welcome. If it (or samething else) didnt work, please create new issue for it and provide more info - what it do, error messages...

**Comment by lavindika** [comment]
Okay Boss.I get your information.The second i test it fails while i`m testing.My fail scenario is 
press exit_kisok and go back to home and select home as default.Then i come back to my app check is
isInKiosk.Then it shows me true.This fails both my one and yours.Then I test this one.This will check package name which is set to the launcher.

**private String findLauncherPackageName(){  
        final Intent intent = new Intent(Intent.ACTION_MAIN); 
        intent.addCategory(Intent.CATEGORY_HOME); 
        final ResolveInfo res = this.cordova.getActivity().getPackageManager().resolveActivity(intent, 0); 
        return res.activityInfo.packageName;**
    }

I check the return package name is my "Application identifier" my package name or else.if it is mine i will say true.if not false.

In kisok.js 

```
**isInKiosk: function (callback) {
    exec(function (out) {
        var res = "Application still unlock. Please change launcher from settings."
        if (out === "com.test.testKisokMode") {
            res = "Locked";
        }
        callback(res);
    }, function(error){
        alert("KioskPlugin.isInKiosk failed: "+error);
    }, "KioskPlugin", "isInKiosk", []);
}**
```

Thanks for your help.Your help is very much appreciate.I like to see more valuable  things from you.Keep it up Boss.

**Comment by thaarok** [comment]
The aim of `isInKiosk()` was to determine which activity (restricted or unrestricted) is running right now. But I can add this as `isSetAsLauncher()` - it will be useful. Thanks :+1:

**Comment by lavindika** [comment]
Okay Bro 👍 .I want see the best form you.Because your plugin help save my days.Keep it up bro.Thank for your`s plugin. :)

**Comment by thaarok** [comment]
It is in :)

**Comment by lavindika** [comment]
Okay Bro :) .I`ll check.Very happy the way your`s work.keep it up.All the best (Y)
