### ISSUE TITLE
fk.fadeit.play does not exist

### ISSUE THREAD

**Issue by osterland** [honza889/cordova-plugin-kiosk#23]
Hey folks, 

i tried to include this plugin to my existing ionic v1 app. After doing so- i get this compilation error: 

/KioskActivity.java:69:
error: package dk.fadeit.play does not exist
i googled, but was unable to find anything helpful. Do you guys have a hint for me?

**Comment by thaarok** [comment]
KioskActivity from this project does not containg anything like it:
https://github.com/honza889/cordova-plugin-kiosk/blob/master/android/KioskActivity.java
Are you sure you are not using some fork?

**Comment by osterland** [comment]
Sorry was my bad - youre right i was using a fork to get the package.json - never mind & thank you
