### ISSUE TITLE
Shutting down

### ISSUE THREAD

**Issue by ramezrafla** [honza889/cordova-plugin-kiosk#24]
Hey again @honza889 

Right now, as soon as the window loses focus the plugin sends the intent `android.intent.action.CLOSE_SYSTEM_DIALOGS` which closes the power down dialog. Is there any way to detect power down attempt and allow it? Searched everywhere and can't find an answer that works.

Thanks a lot for your courtesy and support

**Comment by thaarok** [comment]
I dont think so - application has no permission to work with system dialogs more, I think. You can check Android API, but I had no success when I was trying to archive it too.
Closing as this is not plugin issue.
