### ISSUE TITLE
open application in kiosk

### ISSUE THREAD

**Issue by mohamadnajiya** [honza889/cordova-plugin-kiosk#25]
Hi, 
When I start the application for the first time it doesn't open in kiosk mode.
I need to execute  KioskPlugin.exitKiosk(); then select the application to run it as kisok.

Any ideas what might be the issue?

**Comment by thaarok** [comment]
This is standard behavior - see README:
> To it work user have to set this application as launcher (see below) and start it by pressing Home button.
