### ISSUE TITLE
can exit kiosk without KioskPlugin.exitKiosk();

### ISSUE THREAD

**Issue by fazamutash** [honza889/cordova-plugin-kiosk#26]
Hi @honza889 
I am facing the problem that I can exit kiosk mode just by clicking this button multiple times : 
![image](https://user-images.githubusercontent.com/23185628/28254892-4d536430-6adb-11e7-8ed0-01b292215edc.png)

Is there any solution to make the only way to exit kiosk mode is by calling KioskPlugin.exitKiosk()?

Thanks

**Comment by thaarok** [comment]
Hi, you need to set your application as launcher - home screen of phone - in phone settings. See README.md.

**Comment by thaarok** [comment]
Wait a sec.. what is the button? Is it recent apps button?

**Comment by fazamutash** [comment]
Yap it is recent apps button, I tried to multiple click and it still show recent apps, I can select the real launcher and it breaks the kiosk mode.

**Comment by thaarok** [comment]
Restart device, so the only running task is kiosk application - when there is no more tasks, recent apps will not be shown. (you can still start other apps by intent, but keep them to start in current task)
