### ISSUE TITLE
Multiple instance creation

### ISSUE THREAD

**Issue by aravindh-zan** [honza889/cordova-plugin-kiosk#27]
Hi.
      Your plugin is awesome. I have one problem with the kiosk plugin. Whenever I clicks the home button, it creates a new instance in android. What happens is, for each instance the application is running the process simultaneously. So the application is running same background for more than one time. 

Can you please fix it ASAP?

**Comment by thaarok** [comment]
Can you specify version of Android where it occurs?
Do you mean new instance of KioskActivity? Or HomeActivity ("Click or press any key to begin...") too?

Looks like `android:launchMode="singleTop"` (see plugin.xml) is not applied - check if it is correctly generated into your AndroidManifest.xml.

If you will find the problem, I can fix it ASAP. But not without knowing what has happened to you.

**Comment by g4challenge** [comment]
Can confirm behaviour on Android 7, 
![image](https://user-images.githubusercontent.com/7804472/28308075-65be498e-6ba5-11e7-915e-43df2ec0cea0.png)

the AndroidManifest.xml contains the singleTop entry.

**Comment by aravindh-zan** [comment]
Hi honza889,
       I am using android kitkat and lollipop.  Home Activity is creating multiple instance. My AndroidManifest.xml has singleTop as launch mode. 
![capture](https://user-images.githubusercontent.com/30252793/28313036-e761a012-6bd2-11e7-83ec-0398ebda9522.PNG)

**Comment by thaarok** [comment]
Please re-test with following update, in branch "devel" for now only:

     cordova plugin add https://github.com/honza889/cordova-plugin-kiosk.git#devel

If you confirm all works ok, I will merge it into master.

**Comment by aravindh-zan** [comment]
It is working fine for HomeActivity. But still 2 instance running at the same time. 
        1. When I installs the app, it is creating one instance.
        2. When I set the app as home, it is creating another instance. 
But, previous issue got fixed.

**Comment by thaarok** [comment]
Thanks for confirming 👍 will merge into master.
What you are describing are not 2 instances of the activity, but actually 2 different activities: KioskActivity and default CordovaActivity - will be able to resolve by removing when cordova plugin will be able to remove default cordova activity from android manifest. Last time I was working on this it was only possible to add elements into android manifest.

**Comment by thaarok** [comment]
The 2 instances should be resolved by new .version, which does not create new standalone activities, but replace main activity.
This new experimental version is available in branch "mainactivity".
Can somebody confirm it work for him? :)
To use version from this branch:
```
cordova plugin add https://github.com/hkalina/cordova-plugin-kiosk.git#mainactivity
```
This also removes non-kiosked version of the activity from menu.

**Comment by narigondelsiglo** [comment]
I've tried master and mainactivity branch...
With master I have several activities behaviour, with branch I have only two activities, but it behaves very different: when touch home or recent activities button the screen "flashes", and I'm able to swipe down the status bar (not able to do anything but it shows)

**Comment by thaarok** [comment]
@narigondelsiglo thanks for testing it - will try to rework the status-bar prevention as next step

**Comment by thaarok** [comment]
Resolved in master.
