### ISSUE TITLE
Disable access to recent apps

### ISSUE THREAD

**Issue by SystemParadox** [honza889/cordova-plugin-kiosk#3]
On some devices it may still be possible to access the recent apps list (in my case a Honeywell Dolphin 75e, which has a direct hardware button for recent apps).

I had to add the following code to prevent this (best to add to both KioskActivity and HomeActivity):

```
import android.app.ActivityManager;
import android.content.Context;

public void onWindowFocusChanged(boolean hasFocus) {
    if (! hasFocus) {
        ActivityManager am = (ActivityManager)getSystemService(Context.ACTIVITY_SERVICE);
        am.moveTaskToFront(getTaskId(), ActivityManager.MOVE_TASK_WITH_HOME );
    }
}
```

**Comment by DanielFreiburger** [comment]
Very nice!

Works fine but requires additional permission
`android.permission.REORDER_TASKS`

**Comment by thaarok** [comment]
Thanks for commision to booth.
