### ISSUE TITLE
System UI Tuner

### ISSUE THREAD

**Issue by IgnatevAnton** [honza889/cordova-plugin-kiosk#30]
If you remove the System UI Tuner function, the settings menu opens

**Comment by thaarok** [comment]
Can you provide more info? To enable System UI Tuner you need to go to the notification shade, which should not be possible in kisk mode.

**Comment by IgnatevAnton** [comment]
https://github.com/honza889/cordova-plugin-kiosk/issues/15
Open the notification panel. Enable System UI Tuner. Disabled System UI Tuner.

**Comment by thaarok** [comment]
In such case this is direct consequence of #15 so no need new issue - closing this one.
You can try to use way of blocking suggested in #14 - feel free to sent pull request if it will be working.
