### ISSUE TITLE
Installing via ionic1

### ISSUE THREAD

**Issue by rabbishuki** [honza889/cordova-plugin-kiosk#31]
I have been trying for hours to use your plugin. but to no avail.

It installs successfully, and seems like everything is fine, but when I try to use the `KioskPlugin.exitKiosk()` function, I get the response that `KioskPlugin is not defined`.

I also searched for it in window, plugins, ionic & cordova.plugins but it is nowhere to be seen.

Also, I tried installing a different launcher and now when I press the home button I have two options, but not three. 

Any ideas?

**Comment by thaarok** [comment]
At first ensure your activity is set as launcher - if you dont see this application in available launchers, try to regenerate android code:
```
cordova platform rm android
cordova platform add android
```

**Comment by thaarok** [comment]
Also you may should try to compile and deploy demo application first: https://github.com/honza889/cordova-kiosk-demo

**Comment by rabbishuki** [comment]
Tried that, not working.

This is what my controller looks like, am I missing something? Do I need to add KioskPlugin as a dependency?
```js
app.controller('myCtrl', function($scope, $ionicPopup) {
    ...
    $ionicPopup.show({
        title: 'Enter Password',
        template: '<input type="text" ng-model="manager.password">',
        scope: $scope,
        buttons: [
            {
                text: 'Cancel'
            }, {
                text: 'Confirm',
                type: 'button-positive',
                onTap: function (e) {
                     if ($scope.manager.password !== MY_PASSWORD) {
                          e.preventDefault();
                     } else {
                          KioskPlugin.exitKiosk(); // KioskPlugin is not defined
                          return $scope.manager.password;
                     }
                }
            }
        ]
    });
    ...
});
```

**Comment by thaarok** [comment]
You probably need to call `window.cordova.plugins.KioskPlugin.exitKiosk();`
see https://stackoverflow.com/questions/26786233/access-cordova-plugins-from-ionic-controller.
Reopen if does not help and will look KioskPlugin specific.

**Comment by thaarok** [comment]
check following project, which use this plugin too:
https://github.com/honza889/ict-framework/blob/master/YesNoApp/www/js/ict.js#L44

**Comment by rabbishuki** [comment]
OK, I don't know what the problem was, but I updated the ionic cli, created a new app via the new ionic pro dashboard, and then it started to work.

Thanks for your amazing plugin.
