### ISSUE TITLE
Hide navigationbar

### ISSUE THREAD

**Issue by bjornskov** [honza889/cordova-plugin-kiosk#32]
I have successfully used the plugin to set the app as Launcher.

My next problem is, that is my device (Lenovo Tab 3) got a "quick access" button. This allows the user to bypass the launcher and launch some of the other builtin apps like Music or Mail.

Furthermore it seems that I can still access the statusbar by pulling it down.

I tried to use the fullscreen plugin, but this still allows access by pulling from top or bottom of screen. Then navigationbar and statusbar will open.

How do I make sure that this does not happen?

![screenshot_20170929-025049](https://user-images.githubusercontent.com/1432667/31004281-0a0d74ec-a4f4-11e7-82f5-03ad059d7ecb.png)

**Comment by ngocdaothanh** [comment]
You can use this additional plugin:
https://github.com/ngocdaothanh/cordova-plugin-unswipable-android-status-bar

It adds an invisible window at the top of the screen that swallows all touch events at the area.

I hope cordova-plugin-kiosk will include the code from the above plugin, or at least mention it in its README.

**Comment by kobvel** [comment]
@ngocdaothanh swipe is disabled, but I still able to see it. Do you have any workaround for this?

**Comment by thaarok** [comment]
Can you please verify that it works in feature `overlay` branch?

    cordova plugin add https://github.com/hkalina/cordova-plugin-kiosk.git#overlay

Thanks

**Comment by kobvel** [comment]
@hkalina now it hides it. But I am able to swipe it down. It is not functional after swipe and hides after few seconds, so I think it is a minor issue.

**Comment by thaarok** [comment]
Thanks for confirmation - merged into master ;)
