### ISSUE TITLE
Back not overridden

### ISSUE THREAD

**Issue by Malcx** [honza889/cordova-plugin-kiosk#33]
Nice little plugin, but I'm having trouble with it running on a Samsung Tab and a wileyfox swift.

When back is pressed the device is taken to a screen showing "Click or press any key to begin..." before relaunching the app from the begining.

Obviously I can edit this text out and the time delay until relaunch, but it would be better if nothing happened at all - that is what I suspect the behaviour should be?

The Samsung is running Android 6.0.1
WileyFox running 7.1.2

**Comment by Malcx** [comment]
The following commands replicate this (windows system) under ionic

ionic start blank BackTest
cd BackTest
cordova platform add android
cordova plugin add https://github.com/honza889/cordova-plugin-kiosk.git
cordova build --debug android
cd .\platforms\android\build\outputs\apk\
adb install .android-debug.apk

Press the home button and set as launcher
Press home -> See "Click or press any key to begin..." -> click or wait -> app loads -> press back -> Click or press any key to begin... -> app restarts

**Comment by thaarok** [comment]
The "Click or press any key to begin..." screen is there because web view fails to load web page correctly immediately after device boot.

To prevent back to this screen you can catch back button event using standard ionic api.

**Comment by Malcx** [comment]
OK that makes sense thanks.

I've been trying to capture the back button in the normal way but for some reason that isn't working and the event is still fired. I guess it is probably an issue in another part of my code so I'll investigate there...
