### ISSUE TITLE
Update android app vesrion in kiosk mode

### ISSUE THREAD

**Issue by MarwahTarek** [honza889/cordova-plugin-kiosk#34]
I wanted to ask if it is possible that I can update my app's version while it is a launcher (the only app running on the mobile, ink iosk mode). How can I do such thing> 
Sorry I/m new to this concept and asked about from my supervisor

**Comment by thaarok** [comment]
I havent tested auto updates of the app, but feature added by  @ngocdaothanh should in theory ensure re-lauching the app after it is updated, so all you need is to reinstall the APK.
https://github.com/honza889/cordova-plugin-kiosk/pull/29
Maybe you can try https://github.com/vaenow/cordova-plugin-app-update plugin and share experience...

**Comment by MarwahTarek** [comment]
@honza889 The problem in my case is that the app is going to be installed from the play store with the kiosk plugin, so I was thinking if there is a way to update the app from within the app for example by a URL or something like that?

**Comment by thaarok** [comment]
See the plugin mentioned above. This is not kiosk related problem.

**Comment by MarwahTarek** [comment]
@honza889 ok thank you very much.
