### ISSUE TITLE
On Restart, Select A home App dialog opens

### ISSUE THREAD

**Issue by rabbishuki** [honza889/cordova-plugin-kiosk#35]
I restarted the device to see what would happen, And apparently when the device boots up, it lets you choose which launcher you want to use again.

Now I know that it is impossible to turn off the device, because it is locked in the launcher, But I am afraid that the battery will die (maybe even on purpose), and then on a recharge, the tablet is open to all, they can even uninstall my app...

Could it have to do with the fact that in order to turn off the device I used the `KioskPlugin.exitKiosk()` function?

I don't think it should make a difference since before restart, if I click the home button again it goes strait back in to the app.

Your help please?

**Comment by thaarok** [comment]
The app should be set as default launcher in device settings. In such case there is no choice on system boot up - devices starts directly into the app.

**Comment by ngocdaothanh** [comment]
There's no workaround. You need to **manually** set the app as default launcher in device settings.

**Comment by profitable** [comment]
The same is happening for me on Android 8.1.0, when I restart the phone or shutdown and turn on again, it shows me a dialog which asks me to "Select a Home app" and shows two options "Huawei Home" & "CordovaKioskDemo", when I choose "Huawei Home" it works, but which I choose "CordovaKioskDemo" it shows a black screen and then asks me again to "Select a Home app" and keeps on doing the same. So if I choose "Huawei Home" and go to settings I can see that the Default Home App is set to "none", although I have set it before to "CordovaKioskDemo". And if I set it again to "CordovaKioskDemo" and open "CordovaKioskDemo", it shows a black screen and close the app. Could you please help me figure out the issue. I am testing it on HUAWEI Y5 Prime 2018 Android 8.1.0 if that helps.
