### ISSUE TITLE
still see status bar

### ISSUE THREAD

**Issue by fabifabi** [honza889/cordova-plugin-kiosk#37]
Even in kiosk mode,i can see my status bar (android 4.4.4)
from here,i can go to settings and uninstall the apk..

How to remove it ?

**Comment by ngocdaothanh** [comment]
Use this plugin:
https://github.com/ngocdaothanh/cordova-plugin-unswipable-android-status-bar

**Comment by fabifabi** [comment]
U saved my day :)

**Comment by rabbishuki** [comment]
@fabifabi What version are you using, didn't work for me in version 6.0

**Comment by fabifabi** [comment]
version of ????

**Comment by fabifabi** [comment]
cordova ? this plug in? status bar?

**Comment by rabbishuki** [comment]
Android

**Comment by fabifabi** [comment]
androdi 4.4 for me

2017-11-06 22:31 GMT+01:00 Shuki Gur <notifications@github.com>:

**Comment by thaarok** [comment]
Can you please verify that it works in feature `overlay` branch?

    cordova plugin add https://github.com/hkalina/cordova-plugin-kiosk.git#overlay

Thanks

**Comment by kobvel** [comment]
@hkalina it works well except that fact that you still able to swipe down notification bar. It's not functional but still seems to be not perfect behavior.
<img width="353" alt="screen shot 2018-05-07 at 20 36 49" src="https://user-images.githubusercontent.com/5960224/39702196-9043fc76-5236-11e8-940a-c93bc0203b16.png">
