### ISSUE TITLE
Error at install: Unable to graft xml at selector

### ISSUE THREAD

**Issue by timonsku** [honza889/cordova-plugin-kiosk#49]
I'm getting the following error using the latest git commit aswell as #v2.0
`
Failed to install 'cordova-plugin-kiosk': Error: Unable to graft xml at selector "/manifest/application/activity[@android:label='@string/activity_name']" from "platforms\android\AndroidManifest.xml" during config install`

Is that something I need to set manually? I couldn't find anything mentioned in the readme.

**Comment by thaarok** [comment]
Please specify your build environment and cordova version or create reproducer. Thanks

**Comment by timonsku** [comment]
Sorry of course. I built under Windows 10 with cordova cli 8.0
in my packag.json I specified cordova-android 6.4.0 and cordova 7.0 for this particular project.

**Comment by thaarok** [comment]
Sorry, I has not been able to reproduce. Can you provide your generated AndroidManifest.xml from your compile APT (before adding the plugin)?
Thanks!

**Comment by gijsbeijer** [comment]
No news on this, I'm having the exact same issue
