### ISSUE TITLE
Orientation override

### ISSUE THREAD

**Issue by lughino** [honza889/cordova-plugin-kiosk#5]
After installing the plugin and have selected it as the default launcher, there is an override of orientation preference.
Having it set as "landscape" in my config.xml, this is overwritten and is no longer valid.

Is there a way to avoid this?

Thanks

**Comment by DanielFreiburger** [comment]
Hey Lughino,

in the _KioskActivity.java_ just

`import android.content.pm.ActivityInfo;`

and in the _onCreate_ function add

`setRequestedOrientation(preferences.getString("Orientation", "portrait") == "portrait" ? ActivityInfo.SCREEN_ORIENTATION_PORTRAIT : ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);`

to the end.

Daniel

**Comment by DanielFreiburger** [comment]
Sorry, there seems to be a problem accessing the preferences.
But you can hard code it into your project:

`setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);`

**Comment by lughino** [comment]
Thanks @DanielFreiburger I resolve putting this attribute in plugin.xml:

``` xml
<activity ... android:screenOrientation="sensorLandscape">...</activity>
```
