### ISSUE TITLE
KioskPlugin not loaded (Ionic)

### ISSUE THREAD

**Issue by sameer777** [honza889/cordova-plugin-kiosk#50]
back button and other button is working properly. If I click on middle (Home button) it goes to default launcher. Home button is not locked.

**Comment by thaarok** [comment]
To has kiosk working, the app needs to be set as default launcher.
Check README.md ;)

**Comment by sameer777** [comment]
Hi, I am working on IONIC 1 application. I am using this kiosk plugin. 
On app initialization I got " KioskPlugin not loaded!".
 if (window.KioskPlugin) {
      alert("KioskPlugin loaded...");
      window.KioskPlugin.isInKiosk(function(isIn) {
        $rootScope.isInKiosk = isIn;
        alert("isInKiosk = " + isIn);
      });
    } else {
      $rootScope.isInKiosk = false;
      alert("KioskPlugin not loaded!");
    }

And I put kiosk.exitplugin in logout that time it will logout properly. 

I didn't understand is this plugin loaded or not. When it will loaded. is any code to load this plugin??

**Comment by thaarok** [comment]
Mentioned code should be ok for run in run() method of ionic module. Check whether you have added the plugin correctly.
Following is ok for me:
https://github.com/hkalina/ict-framework/blob/master/YesNoApp/www/js/ict.js#L44
Called from run method:
https://github.com/hkalina/ict-framework/blob/master/YesNoApp/www/js/app.js#L144
Do you use `ionic cordova plugin add` command?

**Comment by sameer777** [comment]
Yes. I used ionic cordova plugin add

**Comment by thaarok** [comment]
Maybe are you using the plugin too soon, before the javascript is fully loaded?
I has added following into `constructor` of `home.ts` and works as expected...
```
if ((<any>window).KioskPlugin) {
alert("KioskPlugin loaded...");
(<any>window).KioskPlugin.isInKiosk(function(isIn) {
alert("isInKiosk = " + isIn);
});
} else {
alert("KioskPlugin not loaded!");
}
```
I have created the testing app using:
```
ionic start myApp tabs
ionic cordova plugin add https://github.com/hkalina/cordova-plugin-kiosk.git
ionic cordova run
```
Maybe you should check Ionic documentation and change place in code where you are doing this work...
Can you describe what have you done differently?
