### ISSUE TITLE
Is it possible to prevent the screen to be turn off with power button?

### ISSUE THREAD

**Issue by gdespirito** [honza889/cordova-plugin-kiosk#52]
I want to prevent the users to turn off the screen of the tablet with the power button. Is that possible with this plugin?

I tried using https://github.com/katzer/cordova-plugin-background-mode but after installing it, the KioskPlugin.exitKiosk() (or any KioskPlugin functioncall) does not work. 

Thanks!

**Comment by thaarok** [comment]
Did you try the mentioned plugin independently? It does not look there should be some interferences...

**Comment by gdespirito** [comment]
Hi Jan,

Yes, I tested them independently.
Your plugin works great by its own. And the other one works as expected
when used with no other plugins.

If I had your plugins installed, as soon as I install the other one, my
button for 'Exit kiosk mode' stop working. *and every other call to
KioskPlugin.

To replicate, just install the mentioned plugin and it should stop working.
I am using Codrova8.


GONZALO DE-SPIRITO ZÚÑIGA | Web Development
*FRESHWORK STUDIO CHILE*


Fijo: 02 - 2979 0059| Móvil: 881 53 776 |  gonzalo@freshworkstudio.com
<gonzalo@freshworkstudio.com>

Cuida el medio ambiente. No imprimas este e-mail a menos que sea necesario.

2018-06-01 16:59 GMT-04:00 Jan Kalina <notifications@github.com>:

**Comment by thaarok** [comment]
I has just added `https://github.com/katzer/cordova-plugin-background-mode.git` into `cordova-kiosk-demo` and both plugins seams working as expected.
Please try to debug your application using Chrome Dev Tools and provide any error message from the console:
https://medium.com/@coderonfleek/debugging-an-ionic-android-app-using-chrome-dev-tools-6e139b79e8d2

**Comment by thaarok** [comment]
Please reopen if you will have error output
