### ISSUE TITLE
Allow Camera?

### ISSUE THREAD

**Issue by spiffyguy** [honza889/cordova-plugin-kiosk#56]
I have a web app with kiosk enabled.  I would like the user to take a picture.  Is it possible to allow things like a camera to run and return safely without being closed prematurely?

Thanks for an excellent plugin!

- Matt

**Comment by thaarok** [comment]
The most simple way can be using HTML5: ;)
https://davidwalsh.name/browser-camera

**Comment by spiffyguy** [comment]
That is true!  I was thinking about that and I agree would be the best solution for a kiosk mode tablet/phone.   Thanks!  This issue can be closed.

- Matt
