### ISSUE TITLE
NFC Reader does not work in kiosk mode

### ISSUE THREAD

**Issue by lughino** [honza889/cordova-plugin-kiosk#6]
The plugin works fine, but in my application I use the NFC reader, but when Kiosk mode is active not get anything to the application.
Is there a way to solve this problem?

**Comment by thaarok** [comment]
Can you specify way you use NFC reader? (link to cordova plugin?)
I think ff it didnt modify code of the CordovaActivity, there should not be a problem.

**Comment by lughino** [comment]
I use this [plugin](https://github.com/Telerik-Verified-Plugins/NFC), but I have the same problem with this [plugin](https://github.com/chariotsolutions/phonegap-nfc).

There seems to be something that does prevent and does not allow the passage of information in the application.

I also tried the [babbelLab](https://github.com/babbelLab/cordova-plugin-kiosk) fork, but the problem is the same.

**Comment by lughino** [comment]
@honza889 you have some ideas on how to solve the problem?
For me this is a big problem!
Any alternative solution is welcome!

**Comment by thaarok** [comment]
Sorry, in source a dont see where could be a problem and I now have not device with NFC, where I could reproduce it.
Does it work when the original CordovaActivity is started? (app is started as usual, not as launcher?)
Does Chrome debugging show some error message? ( https://developer.chrome.com/devtools/docs/remote-debugging )
Does Logcat show some useful error message? ( $ANDROID_HOME/platform-tools/adb logcat )

**Comment by thaarok** [comment]
Need more info. If you can reproduce and provide same debug output, feel free to reopen.
