### ISSUE TITLE
Change launcher label

### ISSUE THREAD

**Issue by llimz** [honza889/cordova-plugin-kiosk#7]
Hello,

When exiting kiosk mode, Android displays the launchers list. The kiosk mode plugin uses the label "Cordova kiosk app launcher" for the application. Is there a way to change it and put a custom label? Thank you.

Jimmy

**Comment by thaarok** [comment]
For now you have to change "android:label" of activity in plugin.xml:
https://github.com/honza889/cordova-plugin-kiosk/blob/master/plugin.xml#L43

(I hope one day I find time and way to do it all configurable...but for now only this way)

**Comment by SystemParadox** [comment]
Why not change it to `@string/activity_name` to use the activity name defined in config.xml?

That's what I've done and it works great.

**Comment by thaarok** [comment]
Great idea, thanks :+1:
