### ISSUE TITLE
Set this application as Launcher

### ISSUE THREAD

**Issue by JoseGeorges8** [honza889/cordova-plugin-kiosk#76]
On the readme it says 

> To has it working, user have to set this application as launcher (see below) and start it by pressing Home button or by restarting the device.

However I don't see any explanation on how to set this application as launcher, I've been trying to research but I'm clueless, could anybody point me to the right path? Thanks!

**Comment by thaarok** [comment]
As mentioned in README.md, there are different steps for different phones, however:

Alcatel / older Android: Settings - Applications - All - (This Application) / Launcher - Clear defaults, after Home press will be asked for default to set

Xiaomi / newer Android: Settings - Installed apps - Defaults - Launcher

**Comment by rathodkaran07** [comment]
Is there anyway we can set the application as launcher programatically?
something like KioskPlugin.setAsLauncher(); and this will set the application to default launcher.
It should ask the user to choose launcher only after user executes KioskPlugin.exitKiosk();

**Comment by thaarok** [comment]
It is not possible to change default lancher from the regular Android app (from security reason), however it seems it should be possible to configure it through ADB (USB debug), if it will help you:
```
adb shell cmd package set-home-activity "package/activity"
adb reboot
```
https://stackoverflow.com/questions/14816780/can-i-use-adb-to-change-the-default-launcher-program
