### ISSUE TITLE
JS call to re-enter Kiosk Mode ?

### ISSUE THREAD

**Issue by sealover06** [honza889/cordova-plugin-kiosk#83]
I have asked a specific custom Android from my vendor.   Scenario is : 
- Kiosk Mode.   perfect   nav bar / status bar /  notification panel not showing AT ALL. PERFECT
- in my web/cordova app,  I press a button to exit Kiosk Mode.   I do things like settings,  ....  
- when I come back to my app,  the kiosk mode is not there anymore.

- Is there a KioskPlugin.enterKioskMode() call ?   thanks.  would this be a big deal to add ?  thanks.

**Comment by thaarok** [comment]
Sorry, this is not possible - kiosk mode needs the application to be started as launcher. The kiosk exit call allows to start usual launcher as standard app. Switching which app is launcher is possible only from system apps. (rooted devices, manufacturer signing necessary)
