### ISSUE TITLE
audiocontrol

### ISSUE THREAD

**Issue by tammo0** [honza889/cordova-plugin-kiosk#9]
Hi @honza889 
Thanks a lot for the very nice work you did here.
Is there a way to allow the user interactions with the volume-control buttons (hardware)?

thanks and greetings

**Comment by thaarok** [comment]
Hi,
sorry, this is not currently configurable, but you can change this if you modify:
https://github.com/honza889/cordova-plugin-kiosk/blob/master/android/KioskActivity.java#L44
If this method return false, button action is propagated and button work. If it return true, it is blocked.

For your case it could be:

``` java
public boolean onKeyDown(int keyCode, KeyEvent event) {
    return ! (keyCode == KEYCODE_VOLUME_DOWN || keyCode == KEYCODE_VOLUME_UP);
}
```

For more detailed info:
https://developer.android.com/reference/android/app/Activity.html#onKeyDown%28int,%20android.view.KeyEvent%29

**Comment by tammo0** [comment]
Hooray, thanks!
this is what worked for me:

``` java
return ! (event.getKeyCode() == KeyEvent.KEYCODE_VOLUME_UP || event.getKeyCode() == KeyEvent.KEYCODE_VOLUME_DOWN);
```

**Comment by thaarok** [comment]
Maybe I could allow this keys in the whole plugin, as they can be catched/handled in Cordova javascript by standard way and keep this for other keys only...

**Comment by halindrome** [comment]
I actually want the back button to work too - and then handle it in the cordova app.  One of the devices we deploy on has a hardware back (and home and overview) button and we don't want to just ignore it.  I assume the same technique would work.

**Comment by thaarok** [comment]
Use the same as above (to prevent ignoring this buttons) and catch the buttons events in Cordova/Ionic (in javascript of your app, idependently on kiosk plugin):
https://cordova.apache.org/docs/en/latest/cordova/events/events.html
(see "volumedownbutton" and "volumeupbutton")

**Comment by fazamutash** [comment]
Hi @honza889 
I want to enable long press power button (hardware) to restart and power off the device?
is there any way to make it happen in kiosk mode?

Thanks

**Comment by thaarok** [comment]
Hi @fazamutash, you can try to archieve it by the same way as above for volume buttons - just check what is keyCode you are trying to permit.

**Comment by fazamutash** [comment]
hi @honza889 , I have tried that but it didn't work. I think, since we have to long press the button to restart and power off, we cannot use onKeyDown. I also have tried to override onKeyLongPress function instead of onKeyDown, but still didn't work.

Another thing is, the problem might not in power button. Becauase, when we pressed the power button, the dialog for restart and power off is shown. But it trigger the onWindowFocusChanged function that close this dialog suddenly after 0.5s.
any other suggestion?

Thanks

**Comment by thaarok** [comment]
@fazamutash sorry, I have missed.
Maybe you can try to set some variable on KEYCODE_POWER down, which would disable onWindowFocusChanged handler for one time...

**Comment by thaarok** [comment]
Original issue (possibility to allow chosen keys) was resolved by new interface:

    KioskPlugin.setAllowedKeys([ 24, 25 ]);

For keyCode numbers check https://developer.android.com/reference/android/view/KeyEvent.html

**Comment by thaarok** [comment]
The allowing of poweroff system window would require to allow other system windows too, which would allow to escape from kiosk. If it does not mind to you, use existKiosk call for it and power the device off after exiting the KioskActivity.
-> closing
